In [1]:
import numpy as np

## Declaring Scalars, vectors and matrices 
### Scalars


In [2]:
s = 5 
s

5

## Vectors

In [3]:
# By default v is a row vector
v = np.array([5, -2, 4])
v

array([ 5, -2,  4])

## Matrices

In [4]:
m = np.array([[5,12,6], [-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Tensors

In [5]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [6]:
m2 = np.array([[9,8,7], [1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [7]:
t = np.array([m1, m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [8]:
t_manual = np.array([[[5, 12, 6], [-3, 0, 14]], [[9,8,7], [1,3,-5]]])
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Data Types

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

In [11]:
# ndarray == n-dimentional array 
type(m)

numpy.ndarray

In [12]:
s_array = np.array(5)
type(s_array)

numpy.ndarray

## Data Shapes

In [13]:
m.shape

(2, 3)

In [14]:
# 
v.shape

(3,)

In [15]:
v.reshape(-1,1)

array([[ 5],
       [-2],
       [ 4]])

In [16]:
v.reshape(-1,1).shape

(3, 1)

In [17]:
# scalars have no shape
#s.shape  # error

In [18]:
s_array.shape

()

In [19]:
t.shape

(2, 2, 3)

## Scalar Addition 

In [20]:
5+5

10

## Matrix Addition /Subtraction

In [21]:
m1.shape , m2.shape

((2, 3), (2, 3))

In [22]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [23]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

## Addition with a scalar

- its elemnet wise addition 

In [24]:
m1 +1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [25]:
v + 1

array([ 6, -1,  5])

## Transpose of a Matrix/Vectors 

In [26]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [27]:
m1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [28]:
m1.shape, m1.T.shape

((2, 3), (3, 2))

In [29]:
m1.T.T

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [30]:
s_arr = np.array([5])
s_arr

array([5])

In [31]:
s_arr.T

array([5])

In [32]:
v

array([ 5, -2,  4])

In [33]:
# 1-D arrays don't get transposed
v.T

array([ 5, -2,  4])

In [34]:
v.shape

(3,)

In [35]:
v1 = v.reshape(3,1)
v1

array([[ 5],
       [-2],
       [ 4]])

In [36]:
v1.shape

(3, 1)

In [37]:
v1t= v1.T
v1t

array([[ 5, -2,  4]])

In [38]:
v1t.shape

(1, 3)

## Dot Product 

In [39]:
x = np.array([2, 8, -4])
y = np.array([1, -7, 3])

In [40]:
np.dot(x, y)

-66

In [41]:
x @ y 

-66

## Scalar * Scalar 

In [42]:
# scalar product 
np.dot(5, 6 )

30

## Scalar * Vector 
- initial vector scaled by 5 

In [43]:
np.dot(5, x)

array([ 10,  40, -20])

## Scalar * Matrix 

In [44]:
A = np.array([[5,12,6], [-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [45]:
A.shape

(2, 3)

In [46]:
3 * A

array([[15, 36, 18],
       [-9,  0, 42]])

## Matrix * Matrix 

In [47]:
B = np.array([[2,8,3], [-1,0,0]])
B

array([[ 2,  8,  3],
       [-1,  0,  0]])

In [48]:
B.shape

(2, 3)

In [49]:
np.dot(A, B.T)

array([[124,  -5],
       [ 36,   3]])

In [50]:
A @ B.T

array([[124,  -5],
       [ 36,   3]])